# Generated by Django 4.1.5 on 2023-01-15 23:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ballkid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=80)),
                ("last_name", models.CharField(max_length=80)),
                ("age", models.IntegerField(default=0)),
                (
                    "image",
                    models.CharField(
                        blank=True, default="api/static/img/none.jpg", max_length=100
                    ),
                ),
                ("num_years_experience", models.IntegerField(default=0)),
                ("is_captain", models.BooleanField(default=False)),
                ("is_chairperson", models.BooleanField(default=False)),
                (
                    "preferred_position",
                    models.CharField(
                        choices=[
                            ("Back", "Back"),
                            ("Net", "Net"),
                            ("Back/Net", "Back/Net"),
                            ("Net/Back", "Net/Back"),
                        ],
                        default="Back",
                        max_length=10,
                    ),
                ),
                (
                    "is_cut",
                    models.CharField(
                        choices=[("true", "T"), ("pending", "P"), ("false", "F")],
                        default="false",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_checked_in", models.BooleanField(default=False)),
                ("current_team", models.IntegerField(default=0)),
                (
                    "finals_team",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Men's Singles", "Ms"),
                            ("Men's Doubles", "Md"),
                            ("Women's Singles", "Ws"),
                            ("Women's Doubles", "Wd"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("Back", "Back"),
                            ("Net", "Net"),
                            ("Back/Net", "Back/Net"),
                            ("Net/Back", "Net/Back"),
                        ],
                        default="Back",
                        max_length=10,
                    ),
                ),
                (
                    "finals_position",
                    models.CharField(
                        choices=[
                            ("Back", "Back"),
                            ("Net", "Net"),
                            ("Back/Net", "Back/Net"),
                            ("Net/Back", "Net/Back"),
                        ],
                        default="Back",
                        max_length=10,
                    ),
                ),
                ("comments", models.TextField(blank=True, default="")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ballkid",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_hour", models.DateTimeField(default=datetime.datetime.now)),
                ("team", models.IntegerField(default=0)),
                (
                    "court",
                    models.CharField(
                        choices=[
                            ("Stadium", "Stadium"),
                            ("Harris", "Harris"),
                            ("Grandstand", "Grandstand"),
                            ("Court 4", "Four"),
                            ("Court 5", "Five"),
                        ],
                        max_length=10,
                    ),
                ),
                ("short_shifted", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(default=0)),
                ("start_date", models.DateField(null=True)),
                ("end_date", models.DateField(null=True)),
                ("show_teams", models.BooleanField(default=False)),
                ("show_finals_teams", models.BooleanField(default=False)),
                ("on_rain_delay", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="TeamHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team", models.IntegerField(default=0)),
                ("start", models.DateTimeField(default=datetime.datetime.now)),
                ("end", models.DateTimeField(null=True)),
                ("duration", models.DurationField(default=datetime.timedelta)),
                (
                    "ballkid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.ballkid"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FinalsHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                (
                    "match_type",
                    models.CharField(
                        choices=[
                            ("Men's Singles", "Ms"),
                            ("Men's Doubles", "Md"),
                            ("Women's Singles", "Ws"),
                            ("Women's Doubles", "Wd"),
                        ],
                        max_length=20,
                    ),
                ),
                ("num_years_experience", models.IntegerField(default=0)),
                (
                    "ballkid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.ballkid"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CutHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("furthest_day", models.DateField(default=datetime.datetime.today)),
                ("num_years_experience", models.IntegerField(default=0)),
                ("self_cut", models.BooleanField(default=False)),
                (
                    "ballkid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.ballkid"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourtAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "court",
                    models.CharField(
                        choices=[
                            ("Stadium", "Stadium"),
                            ("Harris", "Harris"),
                            ("Grandstand", "Grandstand"),
                            ("Court 4", "Four"),
                            ("Court 5", "Five"),
                        ],
                        max_length=10,
                    ),
                ),
                ("count", models.IntegerField(default=0)),
                ("duration", models.DurationField(default=datetime.timedelta)),
                (
                    "ballkid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.ballkid"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CheckinHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("checkin", models.DateTimeField(default=datetime.datetime.now)),
                ("checkout", models.DateTimeField(null=True)),
                ("duration", models.DurationField(default=datetime.timedelta)),
                (
                    "ballkid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.ballkid"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CheckinAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("duration", models.DurationField(default=datetime.timedelta)),
                (
                    "ballkid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.ballkid"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CaptainHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateTimeField(default=datetime.datetime.now)),
                ("end", models.DateTimeField(null=True)),
                ("duration", models.DurationField(default=datetime.timedelta)),
                (
                    "ballkid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_ballkid",
                        to="api.ballkid",
                    ),
                ),
                (
                    "captain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_captain",
                        to="api.ballkid",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CaptainAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField(default=0)),
                ("duration", models.DurationField(default=datetime.timedelta)),
                (
                    "ballkid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_ballkid",
                        to="api.ballkid",
                    ),
                ),
                (
                    "captain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_captain",
                        to="api.ballkid",
                    ),
                ),
            ],
        ),
    ]
