# Generated by Django 4.1.5 on 2023-01-15 18:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=datetime.datetime.today)),
                ("rating", models.FloatField()),
                ("speed_rating", models.FloatField(blank=True, null=True)),
                ("decision_rating", models.FloatField(blank=True, null=True)),
                ("comments", models.TextField(blank=True, default="")),
                (
                    "ratee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratee",
                        to="api.ballkid",
                    ),
                ),
                (
                    "rater",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rater",
                        to="api.ballkid",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CalibrationParams",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("improvement", models.FloatField(blank=True, null=True)),
                ("reviewer_scale", models.FloatField(blank=True, null=True)),
                ("reviewer_offset", models.FloatField(blank=True, null=True)),
                (
                    "ballkid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ballkid",
                        to="api.ballkid",
                    ),
                ),
            ],
        ),
    ]
