# Generated by Django 4.1.5 on 2023-04-13 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_rename_speed_rating_rating_athleticism_rating_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="schedule",
            old_name="day_hour",
            new_name="start",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="short_shifted",
        ),
        migrations.AddField(
            model_name="schedule",
            name="end",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
