# Generated by Django 4.1.5 on 2023-07-16 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_tournament_banner"),
    ]

    operations = [
        migrations.AddField(
            model_name="ballkid",
            name="is_out_of_town",
            field=models.BooleanField(default=False),
        ),
    ]
