# Generated by Django 4.1.5 on 2023-08-02 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0036_ballkid_checkout_comments_ballkid_schedule_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="ballkid",
            name="last_day",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Monday", "Monday"),
                    ("Tuesday", "Tuesday"),
                    ("Wednesday", "Wednesday"),
                    ("Thursday", "Thursday"),
                    ("Friday", "Friday"),
                    ("Saturday", "Saturday"),
                    ("Sunday", "Sunday"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
