# Generated by Django 4.1.5 on 2023-08-02 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0037_ballkid_last_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="banner1_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tournament",
            name="banner2_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tournament",
            name="banner3_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
