# Generated by Django 4.1.5 on 2023-08-11 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0043_rename_content_banner_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="message",
            field=models.TextField(),
        ),
    ]
