# Generated by Django 4.1.5 on 2024-06-29 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0046_alter_captainanalytics_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="captainanalytics",
            name="year",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="checkinanalytics",
            name="year",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="courtanalytics",
            name="year",
            field=models.IntegerField(),
        ),
    ]
