# Generated by Django 4.1.5 on 2024-06-29 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0047_alter_captainanalytics_year_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkinanalytics",
            name="ballkid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.ballkid"
            ),
        ),
    ]
