# Generated by Django 4.1.5 on 2024-07-24 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0051_alter_ballkid_checkout_comments"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ballkid",
            old_name="num_tickets_used",
            new_name="num_tickets",
        ),
        migrations.AlterField(
            model_name="ballkid",
            name="checkout_comments",
            field=models.CharField(
                blank=True,
                choices=[
                    ("End", "End"),
                    ("1pm", "One"),
                    ("2pm", "Two"),
                    ("3pm", "Three"),
                    ("4pm", "Four"),
                    ("5pm", "Five"),
                    ("6pm", "Six"),
                    ("7pm", "Seven"),
                    ("8pm", "Eight"),
                    ("9pm", "Nine"),
                    ("10pm", "Ten"),
                    ("11pm", "Eleven"),
                    ("12am", "Midnight"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ballkid",
            name="last_day",
            field=models.CharField(
                blank=True,
                choices=[
                    ("End", "End"),
                    ("Monday", "Monday"),
                    ("Tuesday", "Tuesday"),
                    ("Wednesday", "Wednesday"),
                    ("Thursday", "Thursday"),
                    ("Friday", "Friday"),
                    ("Saturday", "Saturday"),
                    ("Sunday", "Sunday"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cuthistory",
            name="furthest_day",
            field=models.CharField(
                choices=[
                    ("End", "End"),
                    ("Monday", "Monday"),
                    ("Tuesday", "Tuesday"),
                    ("Wednesday", "Wednesday"),
                    ("Thursday", "Thursday"),
                    ("Friday", "Friday"),
                    ("Saturday", "Saturday"),
                    ("Sunday", "Sunday"),
                ],
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session",
                    models.CharField(
                        choices=[
                            ("Sunday", "Sunday"),
                            ("Monday", "Monday"),
                            ("Tuesday", "Tuesday"),
                            ("Wednesday", "Wednesday"),
                            ("Thursday", "Thursday"),
                            ("Friday AM", "Friday Am"),
                            ("Friday PM", "Friday Pm"),
                            ("Saturday AM", "Saturday Am"),
                            ("Saturday PM", "Saturday Pm"),
                            ("Finals", "Finals"),
                        ],
                        max_length=15,
                    ),
                ),
                ("order", models.IntegerField()),
                ("num_requested", models.IntegerField(default=0)),
                ("num_granted", models.IntegerField(default=0)),
                ("num_delivered", models.IntegerField(default=0)),
                (
                    "ballkid",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.ballkid",
                    ),
                ),
            ],
        ),
    ]
