name: Fly Deploy

on:
  release:
    types: [created]

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Set up fly
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install rcal
        run: |
          eval `ssh-agent -s`
          ssh-add - <<< '${{ secrets.RCAL_SECRET_KEY }}'
          pip install git+ssh://git@github.com/jtiosue/rcal.git

      - name: Run deploy prep script
        run: sh deploy.sh

      - name: Build backend
        run: python manage.py collectstatic --no-input --clear

      - name: Deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy --remote-only --build-arg SSH_KEY=${{ secrets.RCAL_SECRET_KEY }}
